### PR TITLE
GradCAM

### PR DESCRIPTION
**Pull request by abdksyed**
Added GradCAM Module and also, added Plotting GradCAM function in plot_inference module.

### CODE REVIEW

**Comment by abdksyed** [comment]
image
The Images, coming are not perfect, so maybe the _visualize_cam function in the plot_inference, may need some changes.
Have to see how to overlay/add heatmap to actual images, to display the final image.

**Comment by abdksyed** [comment]
or it's possible the issue is the model currently is going till 4x4, and need to change model so it will end at 8x8, and than perform gradcam and see the results.

**Comment by kaustubhharapanahalli** [comment]
@abdksyed I have a code snippet, let me take a look at it and update it here

**Comment by abdksyed** [comment]
@kaustubhharapanahalli 
Can we merge this for now, and mark this as an issue
So I can try it on ResNet with 8x8 as output, and see if the results are not good, than we can change it?

**Pull request merged**
